[package]
name = "evdev"
version = "0.11.2"
authors = ["Corey Richardson <corey@octayn.net>"]
description = "evdev interface for Linux"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/cmr/evdev"
documentation = "https://docs.rs/evdev"
edition = "2018"

[features]
tokio = ["tokio_1", "futures-core"]

[dependencies]
libc = "0.2.89"
bitvec = "0.22"
nix = "0.23"

tokio_1 = { package = "tokio", version = "1.0", features = ["net"], optional = true }
futures-core = { version = "0.3", optional = true }

[dev-dependencies]
tokio_1 = { package = "tokio", version = "1.0", features = ["macros", "rt-multi-thread"] }
itertools = "0.10"

[[example]]
name = "evtest_tokio"
required-features = ["tokio"]
